[client]
toolbarMode = "viewer" # Esconde opções de desenvolvedor

[theme]
base="dark"
primaryColor="#1A87C9"               # Azul da logo
backgroundColor="#08131F"            # Azul escuro elegante
secondaryBackgroundColor="#0F1D2B"   # Painéis
textColor="#FFFFFF"
font="sans serif"


[browser]
gatherUsageStats = false # Remove avisos de coleta de dados